### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/SimpleLogistics#7]
@Malanok1
we can chat here.

**Comment by zer0Kerbal** [comment]
Danke  @Malanok1 
I just need to find out what the filename localization code should be:
```
Localization 
{
	en-us 
	{
		#SimpleLogistics_Module_Plugged = Verbunden?
		#SimpleLogistics_Module_PluggedNet = Stellen Sie eine Verbindung zum Netzwerk her
		#SimpleLogistics_Module_Getinfo = Logistics module für die einfache gemeinsame Nutzung von Ressourcen.
		#SimpleLogistics_WindowTitle = Netzwerk für Logistics
		#SimpleLogistics_Label1 = Aktuelles Schiff
		#SimpleLogistics_Label2 = Verbunden
		#SimpleLogistics_Label3 = Verbindung getrennt
		#SimpleLogistics_Label4 = Plug wechseln
		#SimpleLogistics_Label5 = Resource Pool:
		#SimpleLogistics_Label6 = Ressourcenanfrage
		#SimpleLogistics_Label7 = Schliessen
		#SimpleLogistics_msg1 = Muss gelandet sein, um die Logistik zu nutzen
		#SimpleLogistics_msg2 = Muss gelandet sein, um die Logistik zu nutzen
	}
}
```

**Comment by zer0Kerbal** [comment]
de-de.cfg - now onto Russian. :D
thank you @Malanok1

**Comment by zer0Kerbal** [comment]
new release - includes German, French, Japanese

**Comment by Malanok1** [comment]
Hi, Zer0kerbal, I have already translated it into russian. But CurseForge thought that it is spam. Can you see it?

  
>Воскресенье, 26 января 2020, 0:55 +03:00 от zer0Kerbal <notifications@github.com>:
> 
>de-de.cfg - now onto Russian. :D
>thank you  @Malanok1
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Арсений Маланин
malaninarseny@mail.ru

**Comment by Malanok1** [comment]
Localization { en-us { #SimpleLogistics_Module_Plugged = Подключен? #SimpleLogistics_Module_PluggedNet = Подключитесь к сети #SimpleLogistics_Module_Getinfo = Logistics module для простого обмена ресурсами. #SimpleLogistics_WindowTitle = Сеть для Logistics #SimpleLogistics_Label1 = Текущий аппарат #SimpleLogistics_Label2 = Подключен #SimpleLogistics_Label3 = Отключен #SimpleLogistics_Label4 = Переключите плагин #SimpleLogistics_Label5 = Resource Pool: #SimpleLogistics_Label6 = Запрос ресурсов #SimpleLogistics_Label7 = Закройте #SimpleLogistics_msg1 = Аппарат должен быть приземлён чтобы использовать Logistics #SimpleLogistics_msg2 = Аппарат должен быть приземлён чтобы использовать Logistics } }

  
>Воскресенье, 26 января 2020, 0:55 +03:00 от zer0Kerbal <notifications@github.com>:
> 
>de-de.cfg - now onto Russian. :D
>thank you  @Malanok1
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Арсений Маланин
malaninarseny@mail.ru

**Comment by zer0Kerbal** [comment]
Curse(d)Forge doesn't let me reply - or comment; and only lets me create a message, not reply. I have submitted a bug report - but I do not expect them to do anything. *shrug*

First, thank you. Included the German translation in 2.0.3.0.3 which just was released. 
And thank you for the Russkiy translations as well. I plan on releasing it in 2.0.3.0.4 in a day or so. If you want it now, you can always get it in [here](https://github.com/zer0Kerbal/SimpleLogistics/blob/localization/GameData/SimpleLogistics/Localization/ru.cfg): 

questions: 
логистика? wouldn't that be the word for 'logistics'?
and 'пул ресурсов' for "Resource Pool"?

Respectfully,
Peka
zer0Kerbal@hotmail.com

**Comment by Malanok1** [comment]
Логистика-it doesn`t sound well. It sounds strange for Russians. ) I`m one of them. Write логистика if you want. Пул ресурсов- I don`t know what it is. Pool- means a game or what? So I wouldn`t write пул ресурсов. 

  
>Воскресенье, 26 января 2020, 13:34 +03:00 от zer0Kerbal <notifications@github.com>:
> 
>Curse(d)Forge doesn't let me reply - or comment; and only lets me create a message, not reply. I have submitted a bug report - but I do not expect them to do anything.  shrug
>First, thank you. Included the German translation in 2.0.3.0.3 which just was released.
>And thank you for the Russkiy translations as well. I plan on releasing it in 2.0.3.0.4 in a day or so. If you want it now, you can always get it in  here :
>questions:
>логистика? wouldn't that be the word for 'logistics'?
>and 'пул ресурсов' for "Resource Pool"?
>Respectfully,
>Peka
>zer0Kerbal@hotmail.com
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Арсений Маланин
malaninarseny@mail.ru

**Comment by Malanok1** [comment]
> @Malanok1
> we can chat here.

Hi

**Comment by zer0Kerbal** [comment]
Thank you – translate.google.com is still a machine – not organic and makes many mistakes. 😃

POOL:
[to combine (things, such as resources) in a common pool or effort]
[ To put into a pool, as for common use:]
[ any communal combination of resources, funds, etc: a typing pool. ]
[the combined resources or funds. ]
[a facility or service shared by a group of people:]

All good. 😃 I just saw English words – and know that languages adopt words all the time – hence the tortured nature of the English language. 😝

**Comment by Malanok1** [comment]
> Thank you @Malanok1 – translate.google.com is still a machine – not organic and makes many mistakes. 😃 POOL: [to combine (things, such as resources) in a common pool or effort] [ To put into a pool, as for common use:] [ any communal combination of resources, funds, etc: a typing pool. ] [the combined resources or funds. ] [a facility or service shared by a group of people:] All good. 😃 I just saw English words – and know that languages adopt words all the time – hence the tortured nature of the English language. 😝

Hi, do still need your mod translated into Chinese? I can do it. )

**Comment by Malanok1** [comment]
But not professionally

**Comment by zer0Kerbal** [comment]
> Hi, do still need your mod translated into Chinese? I can do it. )
> But not professionally

I do believe it is already - however, proof-reading it would be great!

**Comment by zer0Kerbal** [comment]
added Russian (thank you) @Malanok1 
added Brazilian Portueuges (thank you) @net-lisias-kspw
added Swedish (translate.google.com)
added Norwegian (translate.google.com)

**Comment by zer0Kerbal** [comment]
Next up:
Hawaiian
Mexican (es-mx)
Italian (it-it)
Nederlands
Dutch
Polish (pl)
1 ?
2 ?
3 ?
4 ?

**Comment by zer0Kerbal** [comment]
🇺🇸 🇪🇸 🇫🇷 🇮🇹 🇧🇷 🇷🇺 🇩🇪 🇨🇳 🇯🇵 🇰🇷 🇳🇴 🇸🇪

**Comment by Malanok1** [comment]
Alright, I`ll proof-read it. Send me the file))

**Comment by zer0Kerbal** [comment]
Thank you.
All the files are on github (and the latest release)
https://github.com/zer0Kerbal/SimpleLogistics/tree/master/GameData/SimpleLogistics/Localization
